version: '3'

services:
  db:
    image: postgres:12.13-alpine3.17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: exams-management-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
